### PR TITLE
Fixes nav link highlight; removes Events link

### LINKED ISSUE #12: nav item not being highlighted correctly when selected

### PR DESCRIPTION
**Pull request by eehitray**
Fixes #12.

**Detailed changelog:**

1. Adds location as state to ensure that nav links receive the updated URL to decide whether they need to be highlighted or not.
2. Removes the "Events" link for the time being, as there currently is no element being rendered with the ID `events`. A future PR adding in an "Events" section could look into bringing the link back in the nav.

### CODE REVIEW

File: src/components/header/header.tsx [hunk 1]
```diff
@@ -1,20 +1,25 @@
...
+    onClick={() => updateLocation(window.location.href)}
+  >
     <Text color={location.endsWith(id) ? "selectedNavColor" : "white"} pr={5}>
       {text}
     </Text>
   </GatsbyLink>
 );
 
 export const Header: React.FC<{ location: any }> = ({ location }) => {
+  const [curLocation, setCurLocation] = useState(location.href);
```
Comment (ahsan8244) [inline src/components/header/header.tsx:22]: better to name it "currentLocation"

**Review by ahsan8244 — APPROVED** [review]
LGTM, just check my comment

File: src/components/header/header.tsx [hunk 2]
```diff
@@ -1,20 +1,25 @@
...
 import { routes } from "./routes";
 import { MobileMenu } from "./mobileMenu";
 
-export const NavItem = ({ text, id, location, isSection }) => (
-  <GatsbyLink to={isSection ? `/#${id}` : `/${id}`} key={id}>
+export const NavItem = ({ text, id, location, isSection, updateLocation }) => (
+  <GatsbyLink
+    to={isSection ? `/#${id}` : `/${id}`}
+    key={id}
+    onClick={() => updateLocation(window.location.href)}
```
Comment (ahsan8244) [inline src/components/header/header.tsx:13]: instead of using the window global, can we use the window prop provided by gatsby instead?

File: src/components/header/header.tsx (hunk 1 above)
Comment (utkarsh867) [reply src/components/header/header.tsx:22]: Do change this
`curLocation` becomes `currentLocation`
`setCurLocation` becomes `setCurrentLocation`

**Review by utkarsh867 — DISMISSED** [review]
